name: Build Libcurl Impersonate for windows
on: [workflow_dispatch]
permissions:
  contents: write
env:
  ZLIB_COMMIT: 09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851
  ZSTD_COMMIT: 794ea1b0afca0f020f4e57b6732332231fb23c70
  BROTLI_COMMIT: ed738e842d2fbdf2d6459e39267a633c4a9b2f5d
  BORINGSSL_COMMIT: 673e61fc215b178a90c0e67858bbf162c8158993
  CURL_TAG: curl-8_15_0 # using tags is less secure, but easier to maintain
  NGHTTP2_COMMIT: 8f44147c385fb1ed93a6f39911eeb30279bfd2dd
  NGHTTP3_TAG: v1.15.0
  NGTCP2_TAG: v1.20.0
  C_ARES_TAG: v1.34.6
  
jobs:
  build-windows:
    name: Build windows binaries
    strategy:
      matrix:
        include:
          - { sys: vcvars64, env: x86_64, runner: windows-latest }
    runs-on: ${{ matrix.runner }}
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      - name: Install python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: lexiforest/curl-impersonate
      - name: Install NASM
        shell: cmd
        run: choco install nasm -y
      
      - name: Replace win/build.bat and win/deps.sh
        shell: pwsh
        run: |
          Get-Location 
          Copy-Item curl-impersonate/build.bat win/build.bat -Force
          Copy-Item curl-impersonate/deps.sh win/deps.sh -Force

      - name: Fetch and patch deps
        shell: bash
        run: ./win/deps.sh
      - name: Export SSL ZSTD &  functions from libcurl.dll
        shell: bash
        run: |
          DEF_FILE="deps/curl/lib/libcurl.def"
          if [[ -f "$DEF_FILE" ]]; then
            echo "        SSL_get_version" >> "$DEF_FILE"
            echo "        SSL_version" >> "$DEF_FILE"
            echo "        ZSTD_decompress" >> "$DEF_FILE"
            echo "        ZSTD_isError" >> "$DEF_FILE"
            echo "        ZSTD_getErrorName" >> "$DEF_FILE"
            echo "Added exports to $DEF_FILE:"
            tail -n 10 "$DEF_FILE"
          else
            echo "Error: $DEF_FILE not found! Check deps/curl/lib/ after deps.sh."
            exit 1
          fi
          
      # - name: Setup tmate session for debugging
      # uses: mxschmitt/action-tmate@v3
      - name: Build libcurl-impersonate
        shell: cmd
        run: ./win/build.bat ${{ matrix.sys }}
        env:
          DISABLE_ASM_ARM64: ${{ matrix.env == 'arm64' && 'true' || 'false' }}
          CL: /W0 /wd4996 /wd4244 /wd4267 /wd4018 /wd4101 /wd4305 /wd4312 /wd4706 /wd4800
      - name: Build tarball
        shell: bash
        run: |
          dir ./packages
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            tar cvzf libcurl-impersonate-${{ github.head_ref || github.ref_name }}.${{ matrix.env }}-win32.tar.gz -C ./packages .
          else
            tar cvzf libcurl-impersonate-${{ matrix.env }}-win_x86_64.tar.gz -C ./packages .
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcurl-impersonate.${{ matrix.env }}-win_x86_64.tar.gz
          path: ./libcurl-impersonate*.tar.gz
      - name: Upload release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: libcurl-impersonate-${{ github.head_ref || github.ref_name }}.${{ matrix.env }}-win_x86_64.tar.gz
